name: retriever
description: Retrieve values from a Map/Json with ease and safety.
version: 1.0.0
repository: https://github.com/cosmopool/retriever

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
