name: retriever
description: Retrieve values from a Map/Json with ease and safety.
version: 1.0.2
repository: https://github.com/cosmopool/retriever

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.9
